# Generated by Django 2.1.4 on 2018-12-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='artical',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
